#!/bin/bash

# old servers
#export MP_SHARED_MEMORY=yes
#export OMP_NUM_THREADS=2 # need to set numthreads in .f90 as well
#ulimit -s unlimited
#export FC='ifort'
#export NETCDFF='/share/apps/netcdf-f/4.4.4-intel'
#export NETCDFFLIBDIR=$NETCDFF/lib
#export NETCDFFINCDIR=$NETCDFF/include
#export NETCDFC='/share/apps/netcdf-c/4.4.1.1-intel'
## export NETCDFC='/share/apps/netcdf-c/4.4.1.1-threadsafe'
#export NETCDFCLIBDIR=$NETCDFC/lib
#export HDF5='/share/apps/hdf5/1.10.0-threadsafe'
## export HDF5='/share/apps/hdf5/intel/1.10.0'
#export HDF5LIBDIR=$HDF5/lib
#export SZIP='/share/apps/szip/2.1'
##export SZIPINCDIR=$SZIP/include
#export SZIPLIBDIR=$SZIP/lib

#ifort -I$NETCDFFINCDIR -c -fast -free TEST_bt_exp16.f90
#ifort -o TEST_bt_exp16 TEST_bt_exp16.o -openmp -L$NETCDFLIBDIR -lnetcdf -lnetcdff -shared-intel 
#./TEST_bt_exp16

# squall
# export MP_SHARED_MEMORY=yes
# export OMP_NUM_THREADS=8
# # need to set numthreads in .f90 as well
# ulimit -s unlimited
# export FC='ifort'
# export NETCDF='/share/apps/netcdf/intel/4.2.1'
# export NETCDFLIBDIR=$NETCDF/lib
# export NETCDFINCDIR=$NETCDF/include
# export HDF5='/share/apps/hdf5/intel/1.8.15'  
# export HDF5LIBDIR=$HDF5/lib
# export SZIP='/share/apps/szip/2.1'
# export SZIPLIBDIR=$SZIP/lib
# 
# ifort -I$NETCDFINCDIR -c -fast -free QIBT_MASTER.f90 -qopenmp -check bounds -g
# ifort -o QIBT_MASTER QIBT_MASTER.o -qopenmp -L$NETCDFLIBDIR -lnetcdf -lnetcdff -shared-intel -L$HDF5LIBDIR -lhdf5_hl -lhdf5
# ./QIBT_MASTER


# new servers
export MP_SHARED_MEMORY=yes
export OMP_NUM_THREADS=8
# need to set numthreads in .f90 as well
ulimit -s unlimited
export FC='ifort'
export NETCDFF='/share/apps/netcdf-f/intel/4.4.4'
export NETCDFFLIBDIR=$NETCDFF/lib
export NETCDFFINCDIR=$NETCDFF/include
export NETCDFC='/share/apps/netcdf-c/intel/4.4.1.1' #'/share/apps/netcdf-c/4.4.1.1'
export NETCDFCLIBDIR=$NETCDFC/lib
export HDF5='/share/apps/hdf5/intel/1.10.1'  #'/share/apps/hdf5/1.10.1-threadsafe'
export HDF5LIBDIR=$HDF5/lib
export SZIP='/share/apps/szip/2.1'
export SZIPLIBDIR=$SZIP/lib


ifort -I$NETCDFFINCDIR -c -fast -free QIBT_MASTER.f90 -qopenmp -check bounds -g
ifort -o QIBT_MASTER QIBT_MASTER.o -qopenmp -L$NETCDFCLIBDIR -lnetcdf -L$NETCDFFLIBDIR -lnetcdff -shared-intel -L$HDF5LIBDIR -lhdf5_hl -lhdf5
./QIBT_MASTER #> print_output_sbasin.txt


# ifort -I$NETCDFFINCDIR -c -fast -free TEST_bt_exp16_totdays.f90 -qopenmp -check bounds -g
# ifort -o TEST_bt_exp16_totdays TEST_bt_exp16_totdays.o -qopenmp -L$NETCDFCLIBDIR -lnetcdf -L$NETCDFFLIBDIR -lnetcdff -shared-intel -L$HDF5LIBDIR -lhdf5_hl -lhdf5
# ./TEST_bt_exp16_totdays


# ifort -I$NETCDFFINCDIR -c -fast -free TEST_function.f90 -qopenmp -check bounds -g
# ifort -o TEST_function TEST_function.o -qopenmp -L$NETCDFCLIBDIR -lnetcdf -L$NETCDFFLIBDIR -lnetcdff -shared-intel -L$HDF5LIBDIR -lhdf5_hl -lhdf5
# ./TEST_function