#!/bin/bash

# loaded modules: 
#Currently Loaded Modulefiles:
#  1) netcdf-c/4.4.1.1-intel   3) cdo/1.8.2                5) ncl/6.4.0                7) intel/17.0.4.196
#  2) netcdf-f/4.4.4-intel     4) nco/4.6.3                6) hdf5/1.10.1-intel

# new servers
export MP_SHARED_MEMORY=yes
export OMP_NUM_THREADS=4
# need to set numthreads in .f90 as well
ulimit -s unlimited
export FC='ifort'
export NETCDFF='/share/apps/netcdf-f/intel/4.4.4'
export NETCDFFLIBDIR=$NETCDFF/lib
export NETCDFFINCDIR=$NETCDFF/include
export NETCDFC='/share/apps/netcdf-c/intel/4.4.1.1' #'/share/apps/netcdf-c/4.4.1.1'
export NETCDFCLIBDIR=$NETCDFC/lib
export HDF5='/share/apps/hdf5/intel/1.10.1'  #'/share/apps/hdf5/1.10.1-threadsafe'
export HDF5LIBDIR=$HDF5/lib
export SZIP='/share/apps/szip/2.1'
export SZIPLIBDIR=$SZIP/lib


ifort -I$NETCDFFINCDIR -c -fast -free QIBT_exp01.f90 -qopenmp -check bounds -g
ifort -o QIBT_exp01_cyclone QIBT_exp01.o -qopenmp -L$NETCDFCLIBDIR -lnetcdf -L$NETCDFFLIBDIR -lnetcdff -shared-intel -L$HDF5LIBDIR -lhdf5_hl -lhdf5 
./QIBT_exp01_cyclone > shell_output_1979-1983.txt # blizzard now on cyclone
#shell_output_1999-2003.txt # hurricane
#shell_output_2009-2013.txt # typhoon
#shell_output_2004-2008.txt # cyclone 












