#!/bin/bash

# loaded modules: 
#Currently Loaded Modulefiles:
#1) intel/17.0.4.196         3) netcdf-f/4.4.4-intel     5) nco/4.6.3                7) hdf5/1.10.1-intel
#2) netcdf-c/4.4.1.1-intel   4) cdo/1.8.2                6) ncl/6.4.0                8) openmpi/1.10.5-intel


# new servers
export MP_SHARED_MEMORY=yes
export OMP_NUM_THREADS=6
# need to set numthreads in .f90 as well
ulimit -s unlimited
export FC='ifort'
export NETCDFF='/share/apps/netcdf-f/intel/4.4.4'
export NETCDFFLIBDIR=$NETCDFF/lib
export NETCDFFINCDIR=$NETCDFF/include
export NETCDFC='/share/apps/netcdf-c/intel/4.4.1.1' #'/share/apps/netcdf-c/4.4.1.1'
export NETCDFCLIBDIR=$NETCDFC/lib
export HDF5='/share/apps/hdf5/intel/1.10.1'  #'/share/apps/hdf5/1.10.1-threadsafe'
export HDF5LIBDIR=$HDF5/lib
export SZIP='/share/apps/szip/2.1'
export SZIPLIBDIR=$SZIP/lib

#export OPENMPI='/share/apps/openmpi/intel/1.10.5'
#export OPENMPILIBDIR=$OPENMPI/lib
#export OPENMPIINCDIR=$OPENMPI/include


ifort -I$NETCDFFINCDIR -c -fast -free QIBT_exp01_tmp.f90 -qopenmp -check bounds -g
#ifort -I$NETCDFFINCDIR -I$OPENMPILIBDIR -c -fast -free QIBT_exp01.f90 -qopenmp -check bounds -g
ifort -o QIBT_exp01_tmp_typhoon QIBT_exp01_tmp.o -qopenmp -L$NETCDFCLIBDIR -lnetcdf -L$NETCDFFLIBDIR -lnetcdff -shared-intel -L$HDF5LIBDIR -lhdf5_hl -lhdf5 
./QIBT_exp01_tmp_typhoon > shell_output_1979-1983.txt 
#shell_output_1994_1998.txt
#shell_output_1999-2003.txt
#shell_output_1979-1983.txt # blizzard now on cyclone
#shell_output_1999-2003.txt # hurricane
#shell_output_2009-2013.txt # typhoon
#shell_output_2004-2008.txt # cyclone 


ifort -I$NETCDFFINCDIR -c -fast -free QIBT_exp02.f90 -qopenmp -check bounds -g
ifort -o QIBT_exp02 QIBT_exp02.o -qopenmp -L$NETCDFCLIBDIR -lnetcdf -L$NETCDFFLIBDIR -lnetcdff -shared-intel -L$HDF5LIBDIR -lhdf5_hl -lhdf5 
./QIBT_exp02 > shell_output_exp02_test.txt 












